---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgresql-hostpath
  namespace: apps
  labels:
    app: postgresql
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: docker.io/hostpath
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-pv
  labels:
    app: postgresql-db
spec:
  storageClassName: postgresql-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv-claim
  namespace: apps
  labels:
    app: postgresql
spec:
  storageClassName: postgresql-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: apps
  labels:
    app: postgresql
data:
  POSTGRES_DB: postgresqldb
  POSTGRES_USER: postgresqluser
  POSTGRES_PASSWORD: postgresqlpassword
---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
  namespace: apps
  labels:
    app: postgresql
spec:
  serviceName: "postgresql-db"
  replicas: 3
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      namespace: apps
      labels:
        app: postgresql
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9187'
    spec:
      containers:
      - name: postgresql-db
        image: tigonguyen/postgresql:latest
        envFrom:
        - configMapRef:
            name: postgresql-config
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgresql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db
  namespace: apps
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql-db