build:
	cd simple-service && $(MAKE) build
	cd postgresql && $(MAKE) build
deploy:
	cd simple-service && $(MAKE) deploy
	cd postgresql && $(MAKE) deploy
clean: 
	cd simple-service && $(MAKE) clean
	cd postgresql && $(MAKE) clean